### ISSUE TITLE
Fix Uppercase letters for build

### ISSUE THREAD

**Issue by heliacer** [heliacer/edutrack#4]
When executing `npm run build`, it shows the following errors:
```
Failed to compile.

./src/app/(auth)/login/page.tsx
10:31  Error: React Hook "useState" is called in function "page: FC" that is neither a React function component nor a custom React Hook function. React component names must start with an uppercase letter. React Hook names must start with the word "use".  react-hooks/rules-of-hooks
```

I think this indicates that the react FC should be Uppercase, so in this case instead of:
 `const page: FC = ()` use `const Page: FC = ()`

Hope this is an easy fix 😃

**Comment by yukinoyuu** [comment]
Acknowledged. I'll work on fixing that and my bindings tomorrow.
